name: Pipeline manual, agendada e por push

on:
  # Execução manual através da aba "Actions" no GitHub
  workflow_dispatch:

  # Execução agendada de segunda a sexta-feira às 8h
  schedule:
    - cron: '0 8 * * 1-5'

  # Execução por push em branches main e feature
  push:
    branches:
      - main
      - feature/**

jobs:
  unit-tests:
    runs-on:  ubuntu-22.04
    steps:
      # clone do projeto
      - uses: actions/checkout@v4    

      #instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      # instalação das dependencias
      - name: Install dependencies
        run: npm install
        
      - name: Execução dos testes unitários
        run: npx mocha

      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report               # Set ID reference for step
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Mocha Tests           # Name of the check run which will be created
          path: '*.json'    # Path to test results
          reporter: mocha-json        # Format of test results
