name: Pipeline manual, agendada e por push

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - main
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npx mocha
